### PR TITLE
Consistent bin folder names

### PR DESCRIPTION
**Pull request by peterdell**
Follow-up to issue #35:

Apple's official naming now is "macos" instead of "macosx", because they are beyond "X" now
Also, Windows now has 32/64 and ARM versions, so naming the folder "windows_x86_64" would be logical.
I plan to have an environment where I can build ARM for Windows, so this would be a preparation.

Please check if this proposal is OK with you.

Kind regards, Peter.

### CODE REVIEW

**Comment by zbyti** [comment]
Maybe providing binaries is pointless? Let everyone compile from source.

**Comment by peterdell** [comment]
No, providing binaries is essential for most people. Installing and configuring FPC in far from simple for somebody who just intends to do some Atari coding.

**Comment by zbyti** [comment]
I don't believe that someone who wants to program in something other than BASIC won't be able to compile mads or mp.

I had no choice as a Linux user :)

but ok, since you provide the binary, there is nothing to talk about.

**Comment by jhusak** [comment]
Agree. Especially setting coding environment on Windows is painfull. 
     
      
       
        Dnia 28 stycznia 2024 17:17 Peter Dell ***@***.***&gt; napisał(a):
       
    
       
         
 No providing binaries is essential for most people. Installing and configuring FPC in far from simple for somebody who just intends to do some Atari coding.

**Pull request merged**
